### ISSUE TITLE
Add contribution guidelines, code of conduct, issue templates

### ISSUE THREAD

**Issue by kabilar** [datajoint/workflow-calcium-imaging#31]
- Mirror the [datajoint/pharus](https://github.com/datajoint/pharus) repository, once it is updated based off of today's discussion.
  ```
  /.github/ISSUE_TEMPLATE/bug_report.md
  /.github/ISSUE_TEMPLATE/feature_request.md
  /.github/ISSUE_TEMPLATE/config.yml
  /CONTRIBUTING.md
  /CODE_OF_CONDUCT.md
  ```

**Comment by CBroz1** [comment]
- [X] Issue templates
- [X] contribution guidelines
- [ ] code of conduct

**Comment by kabilar** [comment]
These items have been added to the repository.
