### ISSUE TITLE
Create light dataset that can be used as demo with `workflow-calcium-imaging`

### ISSUE THREAD

**Issue by kabilar** [datajoint/workflow-calcium-imaging#45]

**Comment by CBroz1** [comment]
- Should include `scanbox` and `scanimage` as examples

**Comment by tdincer** [comment]
> * Should include `scanbox` and `scanimage` as examples

The scanbox data we have is a single 23GB sbx file. Is it possible to trim it (e.g. down to 3-5GB because that's the case for the scanimage data)?

**Comment by CBroz1** [comment]
> The scanbox data we have is a single 23GB sbx file. Is it possible to trim it (e.g. down to 3-5GB because that's the case for the scanimage data)?

The only solution that comes to mind for me would be a hacky local instal of `sbxreader` where you set [max frames](https://github.com/jcouto/sbxreader/blob/main/sbxreader/reader.py#L54) to your own value.

**Comment by tdincer** [comment]
> > The scanbox data we have is a single 23GB sbx file. Is it possible to trim it (e.g. down to 3-5GB because that's the case for the scanimage data)?
> 
> The only solution that comes to mind for me would be a hacky local instal of `sbxreader` where you set [max frames](https://github.com/jcouto/sbxreader/blob/main/sbxreader/reader.py#L54) to your own value.

I wasn't very clear in my question. I'm able to read the data and it has a shape of (7530, 4, 1, 512, 796). The first number in the list is the number of images. The rest shows the plane number, dimensions, etc. If I slice this matrix to get (500, 4, 1, 512, 796), would that be appropriate? Am I breaking anything? Are there any raw data that depends on this?

**Comment by CBroz1** [comment]
> Am I breaking anything? Are there any raw data that depends on this?

I don't know for sure. If you're able to save and reload, I think it would we worth running the light data through the imaging schema. Kabi or Dimitri could then take a look to see if the results look on-part with having a truncated dataset.

**Comment by kabilar** [comment]
Updated my response above.

**Comment by tdincer** [comment]
Thank @kabilar and @CBroz1! I did some search but couldn't find a tool to write data into a `sbx` file. Suite2p or other libraries always convert the data into other formats. So, looks like, we won't have a `scanbox` example for now.

**Comment by kabilar** [comment]
We have now created a light dataset for ScanImage and Suite2p.  On djarchive, see `workflow-calcium-imaging-data-v2`.  We do not currently have a need for the other data formats.
