### ISSUE TITLE
Readme refers to a non-existing notebook

### ISSUE THREAD

**Issue by tdincer** [datajoint/workflow-calcium-imaging#47]
The README.md file refers to a `notebooks/run_workflow.ipynb` file but this file does not seem to exist.

**Comment by kabilar** [comment]
Thanks @tdincer.  We will fix this.

On a related note, we will likely be moving much of our documentation out of the individual `workflow` and `element` READMEs, and into a common location (see [datajoint-elements/install.md](https://github.com/datajoint/datajoint-elements/blob/main/install.md)).
