### ISSUE TITLE
Add pytest for suite2p trigger

### ISSUE THREAD

**Issue by tdincer** [datajoint/workflow-calcium-imaging#49]
This will work on a light djarchive data.
Add `trigger` (test_mode) to test file. Since the default ProcessingTask was `load`, triggering wasn't tested in the original pytest.

**Comment by GeetikaSi** [comment]
Hi @tdincer, I am planning to make additions to the existing test suite to test suite2p trigger this week. Please let me know if you'd have any suggestions for the same. Thank you!

**Comment by tdincer** [comment]
Hi @GeetikaSi I haven't started working on this issue yet. Will you be working on suite2p `load` or suite2p `trigger`? I'm asking this because as far as I know we don't have a test suite to test suite2p `trigger`.

**Comment by GeetikaSi** [comment]
Hi @tdincer, I'll be adding the test for suite2p trigger in [workflow-calcium-imaging test suite.](https://github.com/datajoint/workflow-calcium-imaging/tree/main/tests).
